Fix build release
alibaba-flutter/aspectd pull request #57
Opened 2020-11-10 08:43 UTC by fightcoder

关于release下问题：

因为release 下是aot模式，会进行全局的静态分析（TFA），代码逻辑在：

```
//kernel_front_end.dart
Future<KernelCompilationResults> compileToKernel(
    Uri source, CompilerOptions options,
    {bool includePlatform: false,
    bool aot: false,
    bool useGlobalTypeFlowAnalysis: false,
    Map<String, String> environmentDefines,
    bool enableAsserts: true,
    bool genBytecode: false,
    BytecodeOptions bytecodeOptions,
    bool dropAST: false,
    bool useProtobufTreeShaker: false,
    bool useProtobufTreeShakerV2: false,
    bool minimalKernel: false,
    bool treeShakeWriteOnlyFields: false,
    String fromDillFile: null}) async {
     ...
       // Run global transformations only if component is correct.
       //debug下不执行，release下aot为true会执行
  if ((aot || minimalKernel) && component != null) {
    await runGlobalTransformations(
        options.target,
        component,
        useGlobalTypeFlowAnalysis,
        enableAsserts,
        useProtobufTreeShaker,
        useProtobufTreeShakerV2,
        errorDetector,
        minimalKernel: minimalKernel,
        treeShakeWriteOnlyFields: treeShakeWriteOnlyFields);
        ...
  }
     ...

}
```

比如，执行`flutter  build apk`命令，报错堆栈如下：

```
Invalid argument(s): Iterables do not have same length.                 
#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:92:7)  
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:127:13)
#2      Substitution.fromPairs (package:kernel/type_algebra.dart:242:13)
#3      DirectMethodInvocation.getStaticType (package:kernel/ast.dart:3542:25)
#4      SummaryCollector._staticDartType (package:vm/transformations/type_flow/summary_collector.dart:1173:12)
#5      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:1176:36)
#6      SummaryCollector._makeCall (package:vm/transformations/type_flow/summary_collector.dart:1080:26)
#7      SummaryCollector.visitDirectMethodInvocation (package:vm/transformations/type_flow/summary_collector.dart:1519:12)
#8      DirectMethodInvocation.accept (package:kernel/ast.dart:3528:44) 
#9      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:853:42)
#10     SummaryCollector.visitReturnStatement (package:vm/transformations/type_flow/summary_collector.dart:2058:37)
#11     ReturnStatement.accept (package:kernel/ast.dart:6541:43)        
#12     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:853:42)
#13     List.forEach (dart:core-patch/growable_array.dart:313:8)        
#14     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1923:21)
#15     Block.accept (package:kernel/ast.dart:5873:43)                  
#16     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:853:42)
#17     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:758:9)
#18     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1451:52)
#19     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:287:42)
#20     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#21     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#22     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:437:44)
#23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#24     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
#25     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#26     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1581:23)
#27     Call.apply (package:vm/transformations/type_flow/summary.dart:265:31)
#28     Summary.apply (package:vm/transformations/type_flow/summary.dart:702:33)
#29     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#30     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#31     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#32     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:437:44)
#33     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#34     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
#35     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#36     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1581:23)
#37     Call.apply (package:vm/transformations/type_flow/summary.dart:265:31)
#38     Summary.apply (package:vm/transformations/type_flow/summary.dart:702:33)
#39     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:296:24)
#40     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:212:14)
#41     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#42     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:437:44)
#43     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#44     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:412:12)
#45     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1347:32)
#46     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1290:7)
#47     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1469:14)
#48     transformComponent (package:vm/transformations/type_flow/transformer.dart:78:20)
#49     runGlobalTransformations (package:vm/kernel_front_end.dart:502:5)
#50     compileToKernel (package:vm/kernel_front_end.dart:393:11)       
<asynchronous suspension>                                               
#51     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:542:54)
#52     new Future.<anonymous closure> (dart:async/future.dart:175:37)  
#53     _rootRun (dart:async/zone.dart:1182:47)                         
#54     _CustomZone.run (dart:async/zone.dart:1093:19)                  
#55     _CustomZone.runGuarded (dart:async/zone.dart:997:7)             
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#57     _rootRun (dart:async/zone.dart:1190:13)                         
#58     _CustomZone.run (dart:async/zone.dart:1093:19)                  
#59     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#60     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#61     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)   
#62     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

可以看到是在`TypeFlowAnalysis.process`过程中报错，

具体报错的地方：

```
  DartType getStaticType(StaticTypeContext context) {
   ...
    return Substitution.fromPairs(
            target.function.typeParameters, arguments.types)
        .substituteType(returnType);
  }
```

因为传入`fromPairs`方法两个list参数的长度不一样，通过`Map.fromIterables`转化成Map就会报错。

因为在构建`DirectMethodInvocation`的时候,对`Argument`参数的创建有问题：

```dart
//创建DirectMethodInvocation
final DirectMethodInvocation mockedInvocation = DirectMethodInvocation(
        AsExpression(PropertyGet(ThisExpression(), Name('target')),
            InterfaceType(originalClass, Nullability.legacy)),
        originalStubProcedure,
        AopUtils.concatArguments4PointcutStubCall(originalProcedure));
        
//该方法对Arguments少了types的添加
 static Arguments concatArguments4PointcutStubCall(Member member) [...]

2020-11-12 15:50 UTC, kangwang1988 commented
请移除已经被合并的部分

提供此次变更出错的example，我使用master分支，aop应用的时候，不论是build apk还是build ios都是OK的。

2020-11-12 15:50 UTC, kangwang1988 requested changes

2020-11-12 15:50 UTC, kangwang1988 commented on 0001-aspectd.patch
>  +    defines[kTargetFile] = globals.fs.path
此部分的逻辑已经被合并，请在此次PR移除。

2020-11-12 15:53 UTC, kangwang1988 requested changes

2020-11-12 15:53 UTC, kangwang1988 commented on 0001-aspectd.patch
> +
移除此部分已被合并的代码逻辑。

2020-11-12 15:53 UTC, kangwang1988 commented on 0001-aspectd.patch
>  +    return output;
移除已经被合并的逻辑。

2020-11-13 02:02 UTC, fightcoder commented
> 请移除已经被合并的部分
> 
> 提供此次变更出错的example，我使用master分支，flutter1.22.3 aop应用的时候，不论是build apk还是build ios都是OK的。

作用于抽象方法，比如：
```
@Exectue("package:flutter/src/gestures/recognizer.dart","GestureRecognizer","-invokeCallback")
@pragma("vm:entry-point")
dynamic hookInvokeCallback(PoinrCut pointCut){
...
}
```

2020-11-13 02:05 UTC, fightcoder commented on 0001-aspectd.patch
>  +    return output;
done

2020-11-14 12:00 UTC, kangwang1988 commented
Verified OK
Thanks for your contribution.

2020-11-14 12:01 UTC, kangwang1988 approved these changes

2020-11-14 13:50 UTC, kangwang1988 commented
Closing this pr as merged manually.

2020-11-14 13:50 UTC, closed without merging